exclude_patterns:
- "src/serviceWorker.js"
- "**/*.test.js"

version: "2"         
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
  identical-code:
    enabled: false
